MobilityFirst/GNS

test/edu/umass/cs/gnsclient/client/integrationtests/ServerIntegrationTest.java
When NIO logs are set to FINEST, NUL appears in logs causing grep to switch to binary mode. This fix prevents that.
=> Fix for case when log files contain NUL

src/edu/umass/cs/gnsserver/gnsapp/clientCommandProcessor/commands/account/RemoveAccount.java, src/edu/umass/cs/gnsserver/gnsapp/clientCommandProcessor/commands/account/RemoveGuid.java, test/edu/umass/cs/gnsclient/client/singletests/RemoveGuidTest.java
Fixed RemoveGuid and RemoveAccount to return NO_ERROR when called on
non-existant guids. Also updated RemoveGuidTest to check for 
these cases.
=> MOB-1087 (Removing a removed guid returns an error).

src/edu/umass/cs/gnsserver/main/GNSConfig.java, test/edu/umass/cs/gnsclient/client/integrationtests/ServerIntegrationTest.java
It must have sneaked in during the last merge. Also disabled active code
due to the issue seen in MOB-1095.
=> Removed errant use of "GNSClient client" from ServerIntegration test.

scripts/travis_template.sh, scripts/travis_template.yml, scripts/travis_test.sh
This change introduces a script that can be used to trigger multiple test runs on Travis CI. The same script can also be later used to identify if there were any failures. Typical use cases include measuring the failure rate of GNS at a particular commit in a particular branch. 
Usage:
```
./scripts/travis_test.sh branch:commit-SHA1
( handle [command] rep_times | --status handle [--clean])
Ex: ./scripts/travis_test.sh master:abcde sample_test "ant test" 10
./scripts/travis_test.sh master:abcde sample_test "`cat file.sh`" 10
./scripts/travis_test.sh master:abcde --status sample_test --clean
```
`handle` is a unique identifier used to identify a particular instantiation of the script.
`rep_times` is the number of Travis instances to be started. Each instance runs the `command` for about 50 …
=> Travis script for measuring failure rates

src/edu/umass/cs/gnsclient/client/GNSClientCommands.java
Adds three mutual auth methods for acls to GNSClientCommands. These were left out in a previous commit.
=> Add secure commands to GNSClientCommands

conf/dns/gnsserver.1dns.local.properties, src/edu/umass/cs/gnsserver/gnamed/UdpDnsServer.java
* Revert change in UdpDnsServer that caused the DNS service to only perform local lookups. This was likely a result of someone trying to perform strictly local lookups but not knowing about the DNS_GNS_ONLY config option.
* Add DNS config file for a local DNS server.
To test:
1.  `bin/gpServer.sh -DgigapaxosConfig=conf/dns/gnsserver.1dns.local.properties restart all`
2.  Perform DNS query against server with `nslookup` or a similar tool
Since this is a small commit I recommend rebasing and merging to help keep the git history clean, but that's more of a personal practice.
=> Restore basic DNS with forwarder functionality

src/edu/umass/cs/gnsclient/client/CommandUtils.java, src/edu/umass/cs/gnsclient/client/CryptoUtils.java, src/edu/umass/cs/gnsclient/client/deprecated/examples/ClientAsynchExample.java, src/edu/umass/cs/gnsclient/client/http/HttpClient.java, src/edu/umass/cs/gnsclient/client/testing/ThroughputAsynchMultiClientTest.java
This change requires a detailed writeup
**What this change is doing:**
This change moves usages of `javax.crypto` and related classes in `GNSClient` to a new class `CryptoUtils`. This change aims to make `CryptoUtils` look like a blackbox to other classes so that all methods of `CryptoUtils` take in a `GuidEntry` (not `PublicKey`/`PrivateKey`) and return a string (in some encoding).
**Why is this required:**
j2objc does not support translating crypto related classes to Objective C. This also means that we will not be able to create an instance of Java's `PublicKey` in Objective C. We need to have a nice interface between translated iOS code and native iOS code. `CryptoUtils` provides that interface. The solution is to implement everything in `CryptoUtils` natively, so that there is no …
=> Move crypto stuff to CryptoUtils

scripts/travis_checks.sh
Tests are timing out due to the recent switch from integration tests to singletests. I'll be reducing the number of times tests are repeated temporarily until test optimizations are done. 7 iterations looks like a good number as each iteration is taking ~5mins. Travis times out at 49mins
=> Reduce the number of Travis test iterations from 10 to 7

src/edu/umass/cs/gnsclient/client/GNSClient.java, src/edu/umass/cs/gnsserver/gnsapp/GNSApp.java, src/edu/umass/cs/gnsserver/gnsapp/GNSAppUtil.java
`GNSClient` uses `GNSApp.getRequestStatic()`. This forces `GNSClient` to depend on `GNSApp` (and all its transitive dependencies) even if it is using a single method. Moving the method in question to a new class avoids this dependency.
=> Move `getRequestStatic` from `GNSApp` to `GNSAppUtil`

src/edu/umass/cs/gnscommon/CommandType.java
This change replaces usage of command handler classes with their string representations to avoid dependency in client code.
=> Make CommandType classnames strings

src/edu/umass/cs/gnsclient/client/GNSCommand.java, src/edu/umass/cs/gnsclient/client/http/HttpClient.java, src/edu/umass/cs/gnsclient/client/util/GuidUtils.java, src/edu/umass/cs/gnsclient/client/util/KeyPairUtils.java
This change pushes KeyPair generation methods to KeyPairUtils so that it can be natively implemented. It also pushes few other methods that directly deal with public key bits in client code.
=> KeyPair cleanup

src/edu/umass/cs/gnsserver/utils/DefaultGNSTest.java
Few methods in gigapaxos' `Util` were moved to `UtilServer`. This change fixes such usages in GNS.
=> Update gigapaxos and fix readFileAsString to use UtilServer

src/edu/umass/cs/gnsclient/client/GNSClientCommands.java, src/edu/umass/cs/gnsclient/client/GNSCommand.java, src/edu/umass/cs/gnsclient/client/bugreports/SequentialCreateFieldTimeout.java, src/edu/umass/cs/gnsclient/client/testing/activecode/TestActiveACL.java, src/edu/umass/cs/gnsclient/client/testing/activecode/TestActiveCodeRemoteQueryClient.java, src/edu/umass/cs/gnscommon/CommandType.java, src/edu/umass/cs/gnsserver/database/CassandraRecords.java, src/edu/umass/cs/gnsserver/database/DiskMapRecords.java, src/edu/umass/cs/gnsserver/database/MongoRecords.java, src/edu/umass/cs/gnsserver/database/NoSQLRecords.java, src/edu/umass/cs/gnsserver/gnsapp/NSSelectInfo.java, src/edu/umass/cs/gnsserver/gnsapp/Select.java, src/edu/umass/cs/gnsserver/gnsapp/clientCommandProcessor/commandSupport/FieldAccess.java, src/edu/umass/cs/gnsserver/gnsapp/clientCommandProcessor/commands/select/SelectQuery.java, src/edu/umass/cs/gnsserver/gnsapp/clientSupport/NSGroupAccess.java, src/edu/umass/cs/gnsserver/gnsapp/packet/SelectRequestPacket.java, src/edu/umass/cs/gnsserver/gnsapp/packet/SelectResponsePacket.java, src/edu/umass/cs/gnsserver/gnsapp/recordmap/GNSRecordMap.java, src/edu/umass/cs/gnsserver/gnsapp/recordmap/NameRecord.java, src/edu/umass/cs/gnsserver/gnsapp/recordmap/RecordMapInterface.java, test/edu/umass/cs/gnsclient/client/integrationtests/ServerFailureTests.java, test/edu/umass/cs/gnsclient/client/singletests/SelectTest.java
The old-style select methods are still supported. They return GUIDs. The new methods have an additional fields parameter which can be null to mean all fields. Note that internally null is used to mean old-style select.
=> Added selectRecords methods to client which return a list of full or partial records.

src/edu/umass/cs/gnsserver/gnsapp/Select.java, test/edu/umass/cs/gnsclient/client/singletests/SelectTest.java
selectRecords should honor ACLs in this way for fields that have restricted access:
1) fields that are not accessible in the query should result in no records being returned (existed before)
2) fields that are not accessible in the fields to be returned should be pruned, but the remaining fields can be returned
=> MOB-1237 (selectRecords should honor ACLs)

src/edu/umass/cs/gnsclient/client/GNSClient.java
The support to configure maximum outstanding requests is needed for the capacity measurement experiments.
=> Added the support to set the maximum outstanding request in the GNSClient.

src/edu/umass/cs/gnsserver/gnsapp/clientCommandProcessor/commandSupport/AccountAccess.java, src/edu/umass/cs/gnsserver/gnsapp/clientCommandProcessor/commands/account/RemoveAccount.java, src/edu/umass/cs/gnsserver/gnsapp/clientCommandProcessor/commands/account/RemoveGuid.java, src/edu/umass/cs/gnsserver/utils/DefaultGNSTest.java, test/edu/umass/cs/gnsclient/client/singletests/BatchCreateTest.java
This pull request contains the following changes.
1) I have added a timeout for the batch removal of GUIDs. The file changed is BatchCreateTest.java. The timeout logic is similar to the one used in the GNSClientInternal.java. I have also checked that the removal works in case there is a timeout and the remove account request is reissued. 
2) I have fixed a false BAD_ACCOUNT_ERROR in RemoveAccount.java. In this case, the GNS was not finding the account information for the account it wanted to remove and it was throwing a BAD_ACCOUNT_ERROR. But, the account was already removed because of concurrent or previous command, so the GNS should return a NO_ERROR. 
3) I made some changes to the GUID lookup calls used in the GNS. Some calls were assuming the GUID to be always stored locally, which …
=> Some RemoveAccount and RemoveGuid fixes

src/edu/umass/cs/gnsserver/utils/DefaultGNSTest.java
In this pull request, I have added a default timeout rule for JUnit tests so that the tests don't block indefinitely. The current timeout is set to 300 seconds, as I think there is no individual test that runs for 5 mins. 
This pull request can fail travis checks as it doesn't contain some bug fixes, which are fixed in the subsequent pull requests.
=> Added default timeout rule to tests.

src/edu/umass/cs/gnscommon/packets/CommandPacket.java, src/edu/umass/cs/gnscommon/packets/PacketUtils.java, src/edu/umass/cs/gnsserver/gnsapp/GNSApp.java, src/edu/umass/cs/gnsserver/gnsapp/GNSApplicationInterface.java, src/edu/umass/cs/gnsserver/gnsapp/clientCommandProcessor/commandSupport/CommandHandler.java, src/edu/umass/cs/gnsserver/gnsapp/clientCommandProcessor/commandSupport/FieldAccess.java, src/edu/umass/cs/gnsserver/interfaces/InternalRequestHeader.java
In this pull request, I have added the support for non-blocking selects in the GNS.
The summary of changes is as follows:
1) In the CommandPacket, I have added the support to read a client's address from a JSON representation of a command. The byte array constructor is not supported and throws a run time exception. 
2) In the InternalRequestHeader, I have added the support to store and retrieve client socket address.
3) The places where a command returns null, I have disabled the checking of assertions.
=> Added support for non-blocking selects in the GNS.

src/edu/umass/cs/gnsserver/gnsapp/clientSupport/NSUpdateSupport.java, src/edu/umass/cs/gnsserver/main/GNSConfig.java
In this pull request, I have added a flag that by default disables the logging of GNS updates as INFO logs.
=> Added a flag that by default disables the logging of updates as INFO logs

src/edu/umass/cs/gnsserver/database/MongoRecords.java, src/edu/umass/cs/gnsserver/gnsapp/Select.java, src/edu/umass/cs/gnsserver/gnsapp/clientSupport/NSAccessSupport.java, src/edu/umass/cs/gnsserver/gnsapp/clientSupport/NSAuthentication.java, src/edu/umass/cs/gnsserver/main/GNSConfig.java
In this pull request, I have added the following changes.
1) The ACL checks in select requests doesn't read a name record more than once.
2) A select response from a name server to an entry name server doesn't send the public keys corresponding to GUIDs in the select response. 
3) Minor mongodb index fixing, so that the integer indexes, +1, -1 in mongodb, can also be given as input.
=> Added changes to select and ACL checks

src/edu/umass/cs/gnsserver/gnsapp/packet/SelectRequestPacket.java, src/edu/umass/cs/gnsserver/gnsapp/packet/SelectResponsePacket.java
In this pull requests, I have fixed the following. In the earlier implementation, the name of a SelectRequestPacket was the hash of its select query. So, for different select queries their corresponding SelectRequestPackets had different names. ActiveReplica.java stores demand profiles corresponding to each distinct name. In an experiment, I found that a lot of demand profiles were stored in an active replica, which was also causing trimming and unnecessary reporting of demand profiles to reconfigurators. So, I have fixed the names for the SelectRequestPacket and SelectResponsePacket to "SelectRequest" and "SelectResponse" respectively.
=> Fixed the aribtrary names for select request packets bug.

src/edu/umass/cs/gnscommon/CommandType.java
This fix was already present but a recent merge somehow removed it. I'm pulling this change again.
=> Assign a fake class to CommandClass to avoid NPE in iOS
